tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c6bfff",
        "outline": "#75777f",
        "on-secondary-fixed": "#2a1700",
        "inverse-primary": "#b4c6f4",
        "on-primary-fixed-variant": "#34466d",
        "surface-container-high": "#dee8ff",
        "secondary": "#855300",
        "surface-tint": "#4c5e86",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffddb8",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-low": "#f0f3ff",
        "secondary-container": "#fea619",
        "on-tertiary-fixed-variant": "#4029bb",
        "on-surface-variant": "#44464e",
        "surface-variant": "#d5e3ff",
        "secondary-fixed-dim": "#ffb95f",
        "surface": "#f9f9ff",
        "inverse-on-surface": "#ecf1ff",
        "surface-bright": "#f9f9ff",
        "primary-container": "#0a1f44",
        "surface-container-highest": "#d5e3ff",
        "on-secondary-container": "#684000",
        "on-secondary-fixed-variant": "#653e00",
        "on-primary-container": "#7687b2",
        "tertiary-fixed": "#e4dfff",
        "on-tertiary-fixed": "#160066",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1a0073",
        "outline-variant": "#c5c6cf",
        "surface-container": "#e7eeff",
        "primary": "#00081e",
        "background": "#f9f9ff",
        "on-surface": "#0b1c32",
        "on-primary-fixed": "#041a3f",
        "on-tertiary-container": "#8274ff",
        "on-background": "#0b1c32",
        "on-error": "#ffffff",
        "tertiary": "#060031",
        "primary-fixed-dim": "#b4c6f4",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-dim": "#cbdbf9",
        "inverse-surface": "#223149",
        "primary-fixed": "#d9e2ff"
      },
      fontFamily: {
        "headline": ["Syne", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      }
    },
  },
}
